import type { LocationId, NpcDef, NpcId, ScheduleEntry } from './types';

/**
 * The people of Ald Sethis, a Varo ash-port on the western skirts of Red
 * Mountain, and of the country around it.
 *
 * Every NPC carries a schedule keyed to the world clock. A settlement whose
 * inhabitants are in the same spot at midnight as at noon reads as a diorama;
 * the schedule is cheap and it is most of what makes a town feel inhabited.
 */

export const LOCATIONS = {
  ald_sethis: 'Ald Sethis, town square',
  sethis_docks: 'Ald Sethis, the ash-docks',
  sethis_market: 'Ald Sethis, market row',
  flagon: 'The Ashen Flagon',
  fighters_hall: 'Ironring hall',
  mages_hall: 'Ashen Conclave hall',
  thieves_cellar: 'The cellar beneath the Flagon',
  temple_sethis: 'Shrine of the Three, Ald Sethis',
  hlaalu_counting: 'Varo counting house',
  redoran_hall: 'Korran hall of the ash-watch',
  tel_muran: 'Tel Muran',
  shirenamat: 'Shirenamat, the Shirenamat camp',
  ashfall_road: 'The Ashfall road',
  kaldera_mine: 'Kaldera egg mine',
  gate_of_ash: 'The Gate of Ash',
  wilderness: 'The ashlands',
} as const satisfies Record<LocationId, string>;

const day = (at: LocationId, home: LocationId, out = 8, back = 19): ScheduleEntry[] => [
  { from: out, to: back, at },
  { from: back, to: out, at: home },
];

/**
 * Two people here keep the same address around the clock, and both of them do
 * it for a reason the writing depends on: Falia Beren is lost in the fourth
 * gallery at Kaldera and cannot leave it, and Seryn Othrelas is bleeding on the
 * Ashfall road and has not moved from where she fell. Everybody else has an
 * hour at which they are somewhere other than work — a market run, an evening
 * in the Flagon, a dawn round of the ash-watch. That difference is the whole of
 * what a schedule buys, and without it a settlement is a set of statues.
 */

export const NPCS = {
  varo_hleran: {
    id: 'varo_hleran',
    name: 'Varo Hleran',
    race: 'dunmer',
    sex: 'm',
    faction: 'hlaalu',
    rank: 6,
    personality: 68,
    willpower: 44,
    baseDisposition: 40,
    purse: 900,
    schedule: [
      { from: 7, to: 13, at: 'hlaalu_counting' },
      { from: 13, to: 15, at: 'flagon' },
      { from: 15, to: 21, at: 'hlaalu_counting' },
      { from: 21, to: 7, at: 'hlaalu_counting' },
    ],
    teaches: ['house_hlaalu', 'great_houses', 'hlaalu_ledger'],
    services: ['trade'],
    guard: false,
    essentialTo: ['hl1_writ', 'tg1_ledger'],
  },
  dral_seran: {
    id: 'dral_seran',
    name: 'Dral Seran',
    race: 'dunmer',
    sex: 'm',
    faction: 'redoran',
    rank: 7,
    personality: 40,
    willpower: 72,
    baseDisposition: 30,
    purse: 300,
    schedule: [
      { from: 5, to: 7, at: 'temple_sethis' },
      { from: 7, to: 12, at: 'redoran_hall' },
      { from: 12, to: 14, at: 'sethis_market' },
      { from: 14, to: 20, at: 'redoran_hall' },
      { from: 20, to: 23, at: 'ald_sethis' },
      { from: 23, to: 5, at: 'redoran_hall' },
    ],
    teaches: ['house_redoran', 'great_houses', 'duel_of_honour'],
    services: ['train', 'repair'],
    guard: false,
    essentialTo: ['rd1_duel'],
  },
  nevena_telvo: {
    id: 'nevena_telvo',
    name: 'Nevena Telvo',
    race: 'dunmer',
    sex: 'f',
    faction: 'telvanni',
    rank: 4,
    personality: 55,
    willpower: 66,
    baseDisposition: 25,
    purse: 1400,
    // A Mouth is the one who goes out and speaks for the master, so the
    // afternoon barges are hers to meet in person.
    schedule: [
      { from: 13, to: 16, at: 'sethis_docks' },
      { from: 16, to: 13, at: 'tel_muran' },
    ],
    teaches: ['house_telvanni', 'great_houses', 'four_verses'],
    services: ['trade', 'train'],
    guard: false,
    essentialTo: ['tv1_spore', 'mq2_four_verses'],
  },
  brenn_alvis: {
    id: 'brenn_alvis',
    name: 'Brenn Alvis',
    race: 'breton',
    sex: 'm',
    faction: 'mages',
    rank: 5,
    personality: 52,
    willpower: 58,
    baseDisposition: 45,
    purse: 600,
    schedule: [
      { from: 8, to: 11, at: 'mages_hall' },
      // He buys his own reagents. He does not trust the porters and says so.
      { from: 11, to: 15, at: 'sethis_market' },
      { from: 15, to: 22, at: 'mages_hall' },
      { from: 22, to: 8, at: 'mages_hall' },
    ],
    teaches: ['mages_guild', 'advancement', 'missing_apprentice'],
    services: ['trade', 'train', 'travel'],
    guard: false,
    essentialTo: ['mg1_reagents', 'mg2_missing_apprentice'],
  },
  hrafna_gulhild: {
    id: 'hrafna_gulhild',
    name: 'Hrafna Gulhild',
    race: 'nord',
    sex: 'f',
    faction: 'fighters',
    rank: 6,
    personality: 45,
    willpower: 50,
    baseDisposition: 45,
    purse: 500,
    schedule: [
      { from: 6, to: 12, at: 'fighters_hall' },
      { from: 12, to: 14, at: 'flagon' },
      { from: 14, to: 18, at: 'fighters_hall' },
      { from: 18, to: 23, at: 'flagon' },
      { from: 23, to: 6, at: 'fighters_hall' },
    ],
    teaches: ['fighters_guild', 'advancement', 'smugglers'],
    services: ['train', 'repair'],
    guard: false,
    essentialTo: ['fg1_shipment', 'fg2_nixhound_den'],
  },
  sethri_quiet: {
    id: 'sethri_quiet',
    name: 'Sethri the Quiet',
    race: 'khajiit',
    sex: 'm',
    faction: 'thieves',
    rank: 7,
    personality: 62,
    willpower: 48,
    baseDisposition: 35,
    purse: 800,
    schedule: [
      { from: 21, to: 5, at: 'thieves_cellar' },
      { from: 5, to: 13, at: 'thieves_cellar' },
      { from: 13, to: 21, at: 'flagon' },
    ],
    teaches: ['thieves_guild', 'stolen_goods', 'hlaalu_ledger'],
    services: ['fence', 'train'],
    guard: false,
    essentialTo: ['tg1_ledger', 'tg2_fence_run'],
  },
  curate_arvel: {
    id: 'curate_arvel',
    name: 'Curate Arvel Thys',
    race: 'dunmer',
    sex: 'm',
    faction: 'temple',
    rank: 5,
    personality: 58,
    willpower: 70,
    baseDisposition: 40,
    purse: 250,
    schedule: [
      { from: 5, to: 19, at: 'temple_sethis' },
      { from: 19, to: 21, at: 'ald_sethis' },
      { from: 21, to: 5, at: 'temple_sethis' },
    ],
    teaches: ['tribunal_temple', 'dissident_saints', 'books'],
    services: ['heal', 'trade'],
    guard: false,
    essentialTo: ['sq_pilgrim_seven', 'mq4_dissident_saints'],
  },
  zabamat: {
    id: 'zabamat',
    name: 'Zabamat, Wise Woman',
    race: 'dunmer',
    sex: 'f',
    faction: 'ashlanders',
    rank: 6,
    personality: 60,
    willpower: 78,
    baseDisposition: 20,
    purse: 120,
    schedule: [
      { from: 5, to: 7, at: 'wilderness' },
      { from: 7, to: 5, at: 'shirenamat' },
    ],
    teaches: ['the_ash_wake', 'hollow_star', 'four_verses', 'ashlanders'],
    services: ['heal'],
    guard: false,
    essentialTo: ['mq2_four_verses', 'mq3_hollow_star', 'mq5_ashen_gate'],
  },
  sul_kanet: {
    id: 'sul_kanet',
    name: 'Sul-Kanet, Ashkhan',
    race: 'dunmer',
    sex: 'm',
    faction: 'ashlanders',
    rank: 8,
    personality: 44,
    willpower: 74,
    baseDisposition: 10,
    purse: 200,
    schedule: [
      { from: 6, to: 9, at: 'ashfall_road' },
      { from: 9, to: 20, at: 'shirenamat' },
      { from: 20, to: 6, at: 'shirenamat' },
    ],
    teaches: ['ashlanders', 'hollow_star'],
    services: [],
    guard: false,
    essentialTo: ['mq3_hollow_star'],
  },
  dinara_loras: {
    id: 'dinara_loras',
    name: 'Dinara Loras',
    race: 'dunmer',
    sex: 'f',
    faction: null,
    rank: 0,
    personality: 66,
    willpower: 40,
    baseDisposition: 55,
    purse: 400,
    schedule: [
      { from: 9, to: 11, at: 'sethis_market' },
      { from: 11, to: 2, at: 'flagon' },
      { from: 2, to: 9, at: 'flagon' },
    ],
    teaches: ['latest_rumours', 'ald_sethis', 'little_advice', 'bad_poetry', 'the_widow'],
    services: ['trade'],
    guard: false,
    essentialTo: [],
  },
  captain_selvi: {
    id: 'captain_selvi',
    name: 'Captain Selvi Marion',
    race: 'imperial',
    sex: 'f',
    faction: 'legion',
    rank: 6,
    personality: 50,
    willpower: 62,
    baseDisposition: 40,
    purse: 700,
    schedule: [
      { from: 6, to: 14, at: 'ald_sethis' },
      { from: 14, to: 20, at: 'sethis_docks' },
      { from: 20, to: 6, at: 'ald_sethis' },
    ],
    teaches: ['guards', 'my_bounty', 'smugglers'],
    services: [],
    guard: true,
    essentialTo: [],
  },
  orrin_twopurse: {
    id: 'orrin_twopurse',
    name: 'Orrin Two-Purse',
    race: 'bosmer',
    sex: 'm',
    faction: 'thieves',
    rank: 3,
    personality: 58,
    willpower: 36,
    baseDisposition: 40,
    purse: 1100,
    schedule: [
      { from: 10, to: 18, at: 'sethis_market' },
      { from: 18, to: 1, at: 'sethis_docks' },
      { from: 1, to: 10, at: 'thieves_cellar' },
    ],
    teaches: ['stolen_goods', 'smugglers'],
    services: ['fence', 'trade'],
    guard: false,
    essentialTo: ['tg2_fence_run'],
  },
  llevo_versifier: {
    id: 'llevo_versifier',
    name: 'Llevo the Versifier',
    race: 'dunmer',
    sex: 'm',
    faction: null,
    rank: 0,
    personality: 70,
    willpower: 28,
    baseDisposition: 60,
    purse: 12,
    schedule: [
      { from: 11, to: 15, at: 'flagon' },
      // Reciting at people who are carrying things and cannot decently leave.
      { from: 15, to: 17, at: 'sethis_market' },
      { from: 17, to: 3, at: 'flagon' },
      { from: 3, to: 11, at: 'flagon' },
    ],
    teaches: ['bad_poetry', 'books', 'latest_rumours'],
    services: [],
    guard: false,
    essentialTo: ['sq_bad_poetry'],
  },
  ferisa_andalen: {
    id: 'ferisa_andalen',
    name: 'Ferisa Andalen',
    race: 'dunmer',
    sex: 'f',
    faction: null,
    rank: 0,
    personality: 42,
    willpower: 55,
    baseDisposition: 45,
    purse: 8,
    schedule: [
      { from: 7, to: 12, at: 'sethis_market' },
      { from: 12, to: 19, at: 'ald_sethis' },
      { from: 19, to: 7, at: 'ald_sethis' },
    ],
    teaches: ['the_widow', 'house_hlaalu'],
    services: [],
    guard: false,
    essentialTo: ['sq_widows_debt'],
  },
  gadan_sarothril: {
    id: 'gadan_sarothril',
    name: 'Gadan Sarothril',
    race: 'dunmer',
    sex: 'm',
    faction: null,
    rank: 0,
    personality: 38,
    willpower: 48,
    baseDisposition: 40,
    purse: 90,
    schedule: [...day('kaldera_mine', 'flagon', 6, 18)],
    teaches: ['kaldera_mine', 'blight', 'missing_apprentice'],
    services: ['trade'],
    guard: false,
    essentialTo: ['mg1_reagents', 'mg2_missing_apprentice'],
  },
  kell_blackwater: {
    id: 'kell_blackwater',
    name: 'Kell Blackwater',
    race: 'nord',
    sex: 'm',
    faction: null,
    rank: 0,
    personality: 34,
    willpower: 46,
    baseDisposition: 15,
    purse: 650,
    schedule: [
      { from: 20, to: 6, at: 'sethis_docks' },
      { from: 6, to: 20, at: 'ashfall_road' },
    ],
    teaches: ['smugglers', 'stolen_goods'],
    services: ['trade', 'fence'],
    guard: false,
    essentialTo: ['fg1_shipment'],
  },
  falia_beren: {
    id: 'falia_beren',
    name: 'Falia Beren',
    race: 'breton',
    sex: 'f',
    faction: 'mages',
    rank: 1,
    personality: 48,
    willpower: 44,
    baseDisposition: 50,
    purse: 40,
    // Sealed in the fourth gallery. She is not going anywhere and that is the quest.
    schedule: [{ from: 0, to: 24, at: 'kaldera_mine' }],
    teaches: ['missing_apprentice', 'kaldera_mine'],
    services: [],
    guard: false,
    essentialTo: ['mg2_missing_apprentice'],
  },
  madrel_vandas: {
    id: 'madrel_vandas',
    name: 'Madrel Vandas',
    race: 'dunmer',
    sex: 'm',
    faction: null,
    rank: 0,
    personality: 56,
    willpower: 68,
    baseDisposition: 30,
    purse: 60,
    schedule: [
      { from: 22, to: 4, at: 'temple_sethis' },
      { from: 4, to: 22, at: 'tel_muran' },
    ],
    teaches: ['dissident_saints', 'tribunal_temple', 'four_verses', 'books'],
    services: [],
    guard: false,
    essentialTo: ['mq4_dissident_saints'],
  },
  bemis_alen: {
    id: 'bemis_alen',
    name: 'Bemis Alen',
    race: 'dunmer',
    sex: 'm',
    faction: null,
    rank: 0,
    personality: 54,
    willpower: 40,
    baseDisposition: 50,
    purse: 220,
    schedule: [
      { from: 6, to: 20, at: 'sethis_docks' },
      { from: 20, to: 6, at: 'flagon' },
    ],
    teaches: ['fenwalker', 'ald_sethis', 'ash_storms'],
    services: ['travel'],
    guard: false,
    essentialTo: ['sq_ashfall_caravan'],
  },
  ryn_sadras: {
    id: 'ryn_sadras',
    name: 'Ryn Sadras',
    race: 'dunmer',
    sex: 'm',
    faction: 'redoran',
    rank: 2,
    personality: 30,
    willpower: 52,
    baseDisposition: 25,
    purse: 140,
    schedule: [
      { from: 8, to: 17, at: 'redoran_hall' },
      { from: 17, to: 23, at: 'flagon' },
      { from: 23, to: 8, at: 'redoran_hall' },
    ],
    teaches: ['duel_of_honour', 'house_redoran'],
    services: [],
    guard: false,
    essentialTo: ['rd1_duel'],
  },
  seryn_othrelas: {
    id: 'seryn_othrelas',
    name: 'Seryn Othrelas',
    race: 'dunmer',
    sex: 'f',
    faction: null,
    rank: 0,
    personality: 46,
    willpower: 50,
    baseDisposition: 35,
    purse: 30,
    // Bleeding where she fell. She has not moved and she will not until this is over.
    schedule: [{ from: 0, to: 24, at: 'ashfall_road' }],
    teaches: ['the_ash_wake'],
    services: [],
    guard: false,
    essentialTo: ['mq1_ash_wake'],
  },
} as const satisfies Record<NpcId, NpcDef>;

export const NPC_LIST: readonly NpcDef[] = Object.values(NPCS);

/** Where an NPC is at a given hour. Wrapping entries handle night shifts. */
export function whereIs(npc: NpcDef, hour: number): LocationId {
  for (const s of npc.schedule) {
    const inside = s.from <= s.to ? hour >= s.from && hour < s.to : hour >= s.from || hour < s.to;
    if (inside) return s.at;
  }
  return npc.schedule.length > 0 ? npc.schedule[0].at : 'wilderness';
}
