/**
 * The whole interface skin, as one stylesheet injected at init.
 *
 * Every texture here is generated by an inline SVG filter (feTurbulence) baked
 * into a data URI: paper fibre, leather pebbling, bone speckle. There is no
 * network in this build, so an asset-free skin is the only way to get real
 * grain — and turbulence at these frequencies is indistinguishable from a
 * scanned sheet at UI scale while costing nothing to ship.
 *
 * Rules the skin holds to: no pure white on pure black, no uniform corner
 * radius, no geometric sans. Panels are cut sheets with torn edges pinned to
 * tooled leather; controls are carved bone with the paint worn off the high
 * points.
 */

const FIBRE =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='240' height='240'%3E%3Cfilter id='f'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.75' numOctaves='4' seed='7'/%3E%3CfeColorMatrix values='0 0 0 0 0.30 0 0 0 0 0.24 0 0 0 0 0.15 0 0 0 0.20 0'/%3E%3C/filter%3E%3Crect width='240' height='240' filter='url(%23f)'/%3E%3C/svg%3E\")";

const STAIN =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='420' height='420'%3E%3Cfilter id='s'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.012' numOctaves='3' seed='19'/%3E%3CfeColorMatrix values='0 0 0 0 0.36 0 0 0 0 0.26 0 0 0 0 0.13 0 0 0 0.30 -0.06'/%3E%3C/filter%3E%3Crect width='420' height='420' filter='url(%23s)'/%3E%3C/svg%3E\")";

const HIDE =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='h'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.28 0.42' numOctaves='5' seed='3'/%3E%3CfeColorMatrix values='0 0 0 0 0.09 0 0 0 0 0.06 0 0 0 0 0.04 0 0 0 0.55 0'/%3E%3C/filter%3E%3Crect width='180' height='180' filter='url(%23h)'/%3E%3C/svg%3E\")";

const BONE =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='b'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='1.4 0.35' numOctaves='3' seed='11'/%3E%3CfeColorMatrix values='0 0 0 0 0.20 0 0 0 0 0.17 0 0 0 0 0.11 0 0 0 0.16 0'/%3E%3C/filter%3E%3Crect width='160' height='160' filter='url(%23b)'/%3E%3C/svg%3E\")";

export const CSS = `
#ash-ui{
    --serif:'Palatino Linotype','Book Antiqua',Palatino,'URW Palladio L','Iowan Old Style',Georgia,'Times New Roman',serif;
  --uncial:'Trajan Pro','Optima','Palatino Linotype','Book Antiqua',Palatino,Georgia,serif;
  --p0:#e0d0a4; --p1:#c8b184; --p2:#ab9469; --p3:#87724c;
  --ink:#2b2116; --ink2:#4d3d29; --ink3:#6d5a3f;
  --bone:#d8c9a4; --bone2:#b3a179; --bone3:#8f7d5a; --bone4:#5e5238;
  --hide:#3a2b1d; --hide2:#241a11; --hide3:#0f0b07; --hide-hi:#5c462e;
  --gold:#c8a95e; --gold2:#8b7136;
  --hp:#8e2b21; --hp2:#c8442c; --mp:#31517f; --mp2:#5d8fd6; --fp:#4d6b4f; --fp2:#87ab6e;
  --ember:#c4551f; --ember2:#ff7a2a; --lum:#3fd6c0; --arcane:#8f6bff; --verd:#5f7a63;
  --warn:#b3521f; --bad:#9c2b1c;
  position:fixed; inset:0; z-index:50; pointer-events:none;
  font-family:var(--serif); color:var(--ink);
  font-size:15px; line-height:1.42; -webkit-font-smoothing:antialiased;
  user-select:none; overflow:hidden;
}
#ash-ui, #ash-ui *{ box-sizing:border-box; }
#ash-ui.hidden{ display:none; }
:where(#ash-ui) :where(button,input,select,textarea){ font:inherit; color:inherit; }
#ash-ui :focus{ outline:none; }
#ash-ui :focus-visible{ outline:2px solid var(--gold); outline-offset:2px; }

/* ---------------------------------------------------------------- surfaces */

.ash-parch{
  background-color:#c2a97c;
  background-image:${STAIN}, ${FIBRE},
    radial-gradient(120% 90% at 22% 8%, var(--p0) 0%, var(--p1) 38%, var(--p2) 72%, var(--p3) 100%);
  background-blend-mode:multiply,multiply,normal;
  box-shadow:inset 0 0 90px rgba(58,38,12,.55), inset 0 0 24px rgba(58,38,12,.4),
             inset 0 1px 0 rgba(255,244,214,.4);
}
.ash-hide{
  background-color:#2f2418;
  background-image:${HIDE},
    radial-gradient(140% 120% at 30% 0%, var(--hide-hi) 0%, var(--hide) 40%, var(--hide2) 74%, var(--hide3) 100%);
  background-blend-mode:multiply,normal;
}
.ash-bone{
  background-color:#c3b089;
  background-image:${BONE}, linear-gradient(178deg, var(--bone) 0%, var(--bone2) 56%, var(--bone3) 100%);
  background-blend-mode:multiply,normal;
}

/* ------------------------------------------------------------------ window */

.ash-win{
  position:absolute; pointer-events:auto; display:flex; flex-direction:column;
  padding:15px; color:var(--ink);
  border:1px solid #0b0705;
  box-shadow:0 26px 60px -18px rgba(0,0,0,.86), 0 2px 0 rgba(0,0,0,.5),
             inset 0 0 0 1px rgba(122,95,58,.5), inset 0 0 26px rgba(0,0,0,.55);
  /* Not a rounded rect: the corners are cut, as if the hide were shear-trimmed. */
  clip-path:polygon(12px 0,calc(100% - 12px) 0,100% 12px,100% calc(100% - 12px),
                    calc(100% - 12px) 100%,12px 100%,0 calc(100% - 12px),0 12px);
}
.ash-win > .sheet{
  flex:1; min-height:0; display:flex; flex-direction:column;
  padding:16px 20px 18px;
  box-shadow:0 0 0 1px rgba(30,18,6,.55), 0 6px 18px -6px rgba(0,0,0,.75);
  clip-path:polygon(0 6px,5px 2px,14px 4px,40% 0,62% 3px,calc(100% - 9px) 1px,100% 7px,
                    calc(100% - 3px) 30%,100% 58%,calc(100% - 4px) calc(100% - 5px),
                    calc(100% - 22px) 100%,55% calc(100% - 3px),18% 100%,4px calc(100% - 6px),2px 40%);
}
.ash-win .hdr{
  display:flex; align-items:baseline; gap:14px; margin:-2px 0 10px;
  border-bottom:1px solid rgba(52,34,12,.6); padding-bottom:7px;
  box-shadow:0 1px 0 rgba(255,246,216,.35);
}
.ash-win .hdr h2{
  margin:0; font-family:var(--uncial); font-size:15px; font-weight:400;
  letter-spacing:.30em; text-transform:uppercase; color:#4a3720;
  text-shadow:0 1px 0 rgba(255,246,216,.5);
}
.ash-win .hdr .sub{ font-size:12px; letter-spacing:.14em; color:var(--ink3); margin-left:auto; text-transform:uppercase; }
.ash-win .body{ flex:1; min-height:0; display:flex; gap:16px; }

/* Bone pins holding the sheet to the leather. */
.ash-win .pin{
  position:absolute; width:9px; height:9px; border-radius:50%;
  background:radial-gradient(circle at 34% 30%, #efe2bd 0%, var(--bone2) 55%, #6b5c3c 100%);
  box-shadow:0 1px 2px rgba(0,0,0,.7), inset 0 -1px 1px rgba(0,0,0,.35);
}
.ash-win .pin.tl{ left:6px; top:6px; } .ash-win .pin.tr{ right:6px; top:6px; }
.ash-win .pin.bl{ left:6px; bottom:6px; } .ash-win .pin.br{ right:6px; bottom:6px; }

.ash-scrim{
  position:absolute; inset:0; pointer-events:auto;
  background:radial-gradient(120% 100% at 50% 45%, rgba(10,7,4,.30) 0%, rgba(6,4,2,.74) 100%);
  backdrop-filter:blur(2.5px) saturate(.72);
}

/* ---------------------------------------------------------------- controls */

.ash-btn{
  position:relative; pointer-events:auto; cursor:pointer;
  padding:7px 16px 8px; border:1px solid #241a10; color:#2c2114;
  font-family:var(--uncial); font-size:12px; letter-spacing:.19em; text-transform:uppercase;
  background-color:#c3b089;
  background-image:${BONE}, linear-gradient(178deg,#e2d3ac 0%,#c0ac81 58%,#9a8760 100%);
  background-blend-mode:multiply,normal;
  clip-path:polygon(6px 0,calc(100% - 6px) 0,100% 50%,calc(100% - 6px) 100%,6px 100%,0 50%);
  text-shadow:0 1px 0 rgba(255,247,220,.45);
  transition:filter .13s ease, transform .09s ease;
}
.ash-btn:hover{ filter:brightness(1.10) saturate(1.06); }
.ash-btn:active{ transform:translateY(1px); filter:brightness(.92); }
.ash-btn[disabled]{ filter:grayscale(.7) brightness(.8); cursor:default; }
.ash-btn.wide{ width:100%; }
.ash-btn.grim{
  color:#e6d4ae; background-image:${HIDE}, linear-gradient(178deg,#4a3826 0%,#2c2013 60%,#181008 100%);
  border-color:#0d0905; text-shadow:0 1px 0 rgba(0,0,0,.8);
}
.ash-btn.on{ box-shadow:inset 0 0 0 1px var(--gold), 0 0 12px -2px rgba(200,169,94,.55); }

.ash-tabs{ display:flex; gap:0; margin-bottom:10px; flex-wrap:wrap; }
.ash-tab{
  pointer-events:auto; cursor:pointer; border:0; background:transparent;
  padding:5px 13px 6px; font-family:var(--uncial); font-size:11px; letter-spacing:.2em;
  text-transform:uppercase; color:var(--ink3); border-bottom:2px solid transparent;
}
.ash-tab:hover{ color:var(--ink); }
.ash-tab.sel{ color:#3a2a15; border-bottom-color:var(--gold2); text-shadow:0 1px 0 rgba(255,246,216,.6); }

.ash-slider{ display:flex; align-items:center; gap:10px; }
.ash-slider input[type=range]{
  -webkit-appearance:none; appearance:none; flex:1; height:16px; background:transparent; cursor:pointer;
}
.ash-slider input[type=range]::-webkit-slider-runnable-track{
  height:5px; background:linear-gradient(180deg,#3a2c1c,#5b4830); border:1px solid #1b130c;
  box-shadow:inset 0 1px 2px rgba(0,0,0,.7);
}
.ash-slider input[type=range]::-webkit-slider-thumb{
  -webkit-appearance:none; width:13px; height:19px; margin-top:-8px; border:1px solid #201709;
  background:linear-gradient(180deg,#e6d7b0,#a89263);
  clip-path:polygon(50% 0,100% 26%,100% 74%,50% 100%,0 74%,0 26%);
}
.ash-slider .val{ min-width:44px; text-align:right; font-size:13px; color:var(--ink2); font-variant-numeric:tabular-nums; }

.ash-field{ display:flex; align-items:center; gap:10px; margin:6px 0; }
.ash-field > label{ flex:0 0 154px; font-size:12px; letter-spacing:.13em; text-transform:uppercase; color:var(--ink3); }
.ash-field > *:not(label){ flex:1; }
.ash-input{
  pointer-events:auto; padding:5px 9px; border:1px solid #3d2d1a; color:var(--ink);
  background:rgba(255,246,216,.30); box-shadow:inset 0 1px 3px rgba(60,42,20,.45);
}
.ash-sel{ pointer-events:auto; padding:5px 8px; border:1px solid #3d2d1a; background:rgba(255,246,216,.30); color:var(--ink); }

.ash-check{ display:flex; align-items:center; gap:8px; pointer-events:auto; cursor:pointer;
  background:none; border:0; padding:4px 2px; color:var(--ink2); text-align:left; }
.ash-check i{
  width:14px; height:14px; border:1px solid #2b2013; background:rgba(255,246,216,.28);
  box-shadow:inset 0 1px 2px rgba(0,0,0,.35); display:block; position:relative;
}
.ash-check.on i::after{
  content:''; position:absolute; inset:2px;
  background:linear-gradient(135deg,var(--ember),#7e3312); box-shadow:0 0 6px rgba(196,85,31,.6);
}

/* ------------------------------------------------------------------ scroll */

#ash-ui .scroll{ overflow-y:auto; overflow-x:hidden; scrollbar-width:thin; scrollbar-color:#6d5a3f rgba(60,42,20,.18); }
#ash-ui .scroll::-webkit-scrollbar{ width:9px; }
#ash-ui .scroll::-webkit-scrollbar-track{ background:rgba(60,42,20,.16); }
#ash-ui .scroll::-webkit-scrollbar-thumb{
  background:linear-gradient(90deg,#8a7550,#5b4a30); border:1px solid #2b2013;
}

/* --------------------------------------------------------------------- HUD */

#ash-hud{ position:absolute; inset:0; pointer-events:none; }

.ash-vessels{ position:absolute; left:22px; bottom:30px; display:flex; flex-direction:column; gap:7px; }
.ash-vessel{ position:relative; width:250px; height:23px; filter:drop-shadow(0 3px 4px rgba(0,0,0,.75)); }
.ash-vessel .shell{
  position:absolute; inset:0; border:1px solid #17110a;
  background-color:#a8916a;
  background-image:${BONE}, linear-gradient(180deg,#cdbc94 0%,#94805a 46%,#6a5b3d 100%);
  background-blend-mode:multiply,normal;
  clip-path:polygon(9px 0,calc(100% - 9px) 0,100% 42%,calc(100% - 7px) 100%,7px 100%,0 42%);
  box-shadow:inset 0 1px 0 rgba(255,246,216,.5), inset 0 -2px 4px rgba(0,0,0,.5);
}
.ash-vessel .well{
  position:absolute; inset:4px 7px; overflow:hidden;
  background:linear-gradient(180deg,#120d08,#241a11);
  box-shadow:inset 0 2px 4px rgba(0,0,0,.9);
}
.ash-vessel .fluid{
  position:absolute; inset:0 auto 0 0; width:100%;
  transition:width .34s cubic-bezier(.2,.7,.3,1);
}
/* The meniscus: liquid clings at the leading edge instead of ending in a hard cut. */
.ash-vessel .fluid::after{
  content:''; position:absolute; right:-3px; top:0; bottom:0; width:7px;
  background:linear-gradient(90deg,rgba(255,240,210,.42),rgba(255,240,210,0));
}
.ash-vessel .sheen{
  position:absolute; inset:4px 7px; pointer-events:none;
  background:linear-gradient(180deg,rgba(255,247,222,.30) 0%,rgba(255,247,222,.06) 34%,
             rgba(0,0,0,0) 52%,rgba(0,0,0,.34) 100%);
}
.ash-vessel .num{
  position:absolute; right:9px; top:50%; transform:translateY(-50%);
  font-size:11px; letter-spacing:.06em; color:#fbf1d6; font-variant-numeric:tabular-nums;
  text-shadow:0 1px 3px rgba(0,0,0,1); opacity:.95;
}
.ash-vessel .tag{
  position:absolute; left:9px; top:50%; transform:translateY(-50%);
  font-family:var(--uncial); font-size:9px; letter-spacing:.28em; text-transform:uppercase;
  color:#efe0ba; opacity:.55; text-shadow:0 1px 2px rgba(0,0,0,.9);
}
.ash-vessel.hp .fluid{ background:linear-gradient(180deg,#c8442c,#8e2b21 58%,#4c1610); }
.ash-vessel.mp .fluid{ background:linear-gradient(180deg,#6ea0e6,#31517f 58%,#161f36); }
.ash-vessel.fp .fluid{ background:linear-gradient(180deg,#93b877,#4d6b4f 58%,#1e2a1d); }
.ash-vessel.low .shell{ animation:ash-throb 1.5s ease-in-out infinite; }
@keyframes ash-throb{ 0%,100%{ filter:none; } 50%{ filter:brightness(1.34) sepia(.3); } }

.ash-readied{ position:absolute; right:22px; bottom:20px; display:flex; gap:9px; align-items:flex-end; }
.ash-ready{
  width:58px; height:58px; position:relative; border:1px solid #17110a;
  background-color:#2c2014;
  background-image:${HIDE}, linear-gradient(160deg,#4b3925,#1a120b);
  background-blend-mode:multiply,normal;
  clip-path:polygon(8px 0,calc(100% - 8px) 0,100% 8px,100% calc(100% - 8px),
                    calc(100% - 8px) 100%,8px 100%,0 calc(100% - 8px),0 8px);
  box-shadow:0 3px 8px rgba(0,0,0,.7), inset 0 0 0 1px rgba(160,128,80,.28);
  display:flex; align-items:center; justify-content:center;
}
.ash-ready .glyph{ font-size:25px; line-height:1; filter:drop-shadow(0 1px 2px rgba(0,0,0,.8)); }
.ash-ready .lbl{
  position:absolute; left:0; right:0; bottom:-15px; text-align:center; font-size:9px;
  letter-spacing:.18em; text-transform:uppercase; color:#b9a67c; text-shadow:0 1px 2px #000;
  white-space:nowrap; overflow:hidden; text-overflow:ellipsis;
}
.ash-ready .cond{ position:absolute; left:4px; right:4px; bottom:4px; height:2px; background:rgba(0,0,0,.6); }
.ash-ready .cond i{ display:block; height:100%; background:linear-gradient(90deg,var(--verd),#8fae7a); }
.ash-ready.spell .glyph{ color:var(--arcane); text-shadow:0 0 10px rgba(143,107,255,.75); }

.ash-compass{
  position:absolute; top:14px; left:50%; transform:translateX(-50%);
  width:min(560px,46vw); height:30px; overflow:hidden; opacity:.96;
  background:linear-gradient(180deg,rgba(10,7,3,.55),rgba(10,7,3,0));
  filter:drop-shadow(0 1px 2px rgba(0,0,0,.9));
  -webkit-mask-image:linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent);
  mask-image:linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent);
}
.ash-compass .strip{ position:absolute; top:0; bottom:0; left:0; width:100%; }
.ash-compass .tick{
  position:absolute; top:13px; width:1px; height:5px; background:rgba(226,208,166,.5); transform:translateX(-50%);
}
.ash-compass .tick.major{ top:11px; height:8px; background:rgba(240,226,189,.8); }
.ash-compass .card{
  position:absolute; top:-1px; transform:translateX(-50%); font-family:var(--uncial);
  font-size:12px; letter-spacing:.14em; color:#e9d9ae; text-shadow:0 1px 3px rgba(0,0,0,.95);
}
.ash-compass .mark{
  position:absolute; top:2px; transform:translateX(-50%); font-size:11px; color:var(--lum);
  text-shadow:0 0 8px rgba(63,214,192,.7);
}
.ash-compass .needle{
  position:absolute; left:50%; top:0; width:1px; height:22px; transform:translateX(-50%);
  background:linear-gradient(180deg,var(--gold),rgba(200,169,94,0));
}

.ash-effects{ position:absolute; right:22px; top:52px; display:flex; flex-direction:column; gap:6px; align-items:flex-end; }
.ash-eff{
  display:flex; align-items:center; gap:7px; padding:3px 8px 3px 6px;
  background:linear-gradient(90deg,rgba(20,14,8,0),rgba(20,14,8,.72));
  border-right:2px solid var(--arcane);
}
.ash-eff .g{ font-size:15px; filter:drop-shadow(0 0 5px rgba(143,107,255,.6)); }
.ash-eff .n{ font-size:11px; letter-spacing:.1em; color:#dcc9a0; text-shadow:0 1px 2px #000; }
.ash-eff .t{ font-size:11px; color:#9d8a63; font-variant-numeric:tabular-nums; min-width:26px; text-align:right; }
.ash-eff.bad{ border-right-color:var(--bad); }
.ash-eff.bad .g{ filter:drop-shadow(0 0 5px rgba(156,43,28,.7)); }

.ash-cross{ position:absolute; left:50%; top:50%; width:26px; height:26px; transform:translate(-50%,-50%); }
.ash-cross i{
  position:absolute; background:rgba(240,228,198,.85); box-shadow:0 0 3px rgba(0,0,0,1);
  transition:transform .16s cubic-bezier(.2,.8,.3,1), background-color .16s;
}
.ash-cross i.n{ left:50%; top:0; width:1px; height:7px; margin-left:-.5px; }
.ash-cross i.s{ left:50%; bottom:0; width:1px; height:7px; margin-left:-.5px; }
.ash-cross i.w{ top:50%; left:0; height:1px; width:7px; margin-top:-.5px; }
.ash-cross i.e{ top:50%; right:0; height:1px; width:7px; margin-top:-.5px; }
.ash-cross.hot i{ background:var(--lum); box-shadow:0 0 7px rgba(63,214,192,.85); }
.ash-cross.hot i.n{ transform:translateY(-4px); } .ash-cross.hot i.s{ transform:translateY(4px); }
.ash-cross.hot i.w{ transform:translateX(-4px); } .ash-cross.hot i.e{ transform:translateX(4px); }
.ash-cross.foe i{ background:var(--hp2); box-shadow:0 0 7px rgba(200,68,44,.85); }
.ash-hover{
  position:absolute; left:50%; top:calc(50% + 24px); transform:translateX(-50%);
  font-size:12px; letter-spacing:.14em; text-transform:uppercase; color:#e2d0a6;
  text-shadow:0 1px 3px #000; white-space:nowrap; opacity:0; transition:opacity .15s;
}
.ash-hover.on{ opacity:.95; }

.ash-log{ position:absolute; left:22px; top:16px; width:min(430px,34vw); display:flex; flex-direction:column; gap:3px; }
.ash-msg{
  font-size:14px; color:#e6d6ae; text-shadow:0 1px 3px rgba(0,0,0,.95);
  padding-left:11px; border-left:2px solid rgba(200,169,94,.55);
  animation:ash-in .3s ease-out both; transition:opacity .8s ease;
}
.ash-msg.quest{ color:var(--gold); border-left-color:var(--gold); }
.ash-msg.warn{ color:#e39a6c; border-left-color:var(--warn); }
.ash-msg.fade{ opacity:0; }
@keyframes ash-in{ from{ opacity:0; transform:translateX(-8px); } to{ opacity:1; transform:none; } }

.ash-subtitle{
  position:absolute; left:50%; bottom:96px; transform:translateX(-50%); max-width:52vw; text-align:center;
  font-size:17px; font-style:italic; color:#eadcb6; text-shadow:0 2px 5px rgba(0,0,0,.98);
}

/* --------------------------------------------------------------- inventory */

/* The doll carries all twenty slots the RPG layer defines, in ten rows. It is
   the main axis of a column here, so the basis is its height, not its width. */
.ash-doll{ position:relative; width:212px; flex:1 1 320px; min-height:320px; }
.ash-doll .figure{
  position:absolute; inset:24px 52px 20px 52px;
  background:radial-gradient(60% 46% at 50% 15%, rgba(70,52,28,.34), rgba(70,52,28,0) 70%),
             radial-gradient(48% 40% at 50% 58%, rgba(70,52,28,.30), rgba(70,52,28,0) 72%);
}
.ash-doll .figure svg{ width:100%; height:100%; opacity:.5; }
.ash-slot{
  position:absolute; width:34px; height:34px; pointer-events:auto; cursor:pointer;
  border:1px solid #4a3520; background:rgba(40,27,12,.42);
  box-shadow:inset 0 2px 5px rgba(0,0,0,.6), 0 1px 0 rgba(255,246,216,.35);
  display:flex; align-items:center; justify-content:center; font-size:16px;
  clip-path:polygon(5px 0,calc(100% - 5px) 0,100% 5px,100% calc(100% - 5px),
                    calc(100% - 5px) 100%,5px 100%,0 calc(100% - 5px),0 5px);
}
.ash-slot .ghost{ font-size:13px; opacity:.24; }
.ash-slot.drop{ box-shadow:inset 0 0 0 1px var(--lum), 0 0 14px -2px rgba(63,214,192,.7); background:rgba(63,214,192,.12); }
.ash-slot.filled{ background:rgba(70,52,28,.5); border-color:#5d4526; }

.ash-items{ flex:1; min-width:0; display:flex; flex-direction:column; }
.ash-row{
  display:flex; align-items:center; gap:9px; padding:3px 8px; pointer-events:auto; cursor:pointer;
  border-bottom:1px dotted rgba(80,58,30,.34);
}
.ash-row:hover, .ash-row.sel{ background:linear-gradient(90deg,rgba(120,92,48,.30),rgba(120,92,48,.05)); }
.ash-row .g{ width:20px; text-align:center; font-size:15px; }
.ash-row .n{ flex:1; min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
.ash-row .w, .ash-row .v{ font-size:12px; color:var(--ink3); font-variant-numeric:tabular-nums; }
.ash-row .w{ width:46px; text-align:right; } .ash-row .v{ width:58px; text-align:right; }
.ash-row.eq .n::after{ content:' ⟡'; color:var(--gold2); }
.ash-row.ench .n{ color:#4a3a6b; }
.ash-row.drag{ opacity:.4; }

.ash-cols{
  display:flex; gap:9px; padding:2px 8px 5px; font-size:10px; letter-spacing:.18em;
  text-transform:uppercase; color:var(--ink3); border-bottom:1px solid rgba(60,42,20,.4);
}
.ash-cols button{ background:none; border:0; padding:0; cursor:pointer; pointer-events:auto; color:inherit;
  font:inherit; letter-spacing:inherit; text-transform:inherit; }
.ash-cols button.sel{ color:#3d2c15; text-decoration:underline; }
.ash-cols .g{ width:20px; } .ash-cols .n{ flex:1; text-align:left; }
.ash-cols .w{ width:46px; text-align:right; } .ash-cols .v{ width:58px; text-align:right; }

.ash-enc{ display:flex; align-items:center; gap:10px; margin-top:8px; font-size:12px; }
.ash-enc .bar{ flex:1; height:7px; background:rgba(30,21,12,.6); border:1px solid #2a1e12; position:relative; }
.ash-enc .bar i{ display:block; height:100%; background:linear-gradient(90deg,#7a6a44,#b39a5f); transition:width .3s; }
.ash-enc.near .bar i{ background:linear-gradient(90deg,#a2661f,#d78f36); }
.ash-enc.over .bar i{ background:linear-gradient(90deg,#7e2015,#c0392a); }
.ash-enc.over .num, .ash-enc.near .num{ color:var(--bad); font-weight:600; }
.ash-enc .num{ font-variant-numeric:tabular-nums; color:var(--ink2); }

.ash-preview{
  position:relative; width:212px; height:170px; margin-top:8px; border:1px solid #2b2013;
  background:radial-gradient(70% 70% at 50% 40%, #241a10, #0c0805);
  box-shadow:inset 0 0 20px rgba(0,0,0,.85);
  clip-path:polygon(8px 0,calc(100% - 8px) 0,100% 8px,100% calc(100% - 8px),
                    calc(100% - 8px) 100%,8px 100%,0 calc(100% - 8px),0 8px);
}
.ash-preview canvas{ position:absolute; inset:0; width:100%; height:100%; display:block; }
.ash-preview .cap{
  position:absolute; left:0; right:0; bottom:3px; text-align:center; font-size:10px;
  letter-spacing:.2em; text-transform:uppercase; color:#9d8a63;
}

/* ---------------------------------------------------------------- tooltips */

.ash-tt{
  position:fixed; z-index:60; pointer-events:none; max-width:284px; padding:9px 12px 11px;
  border:1px solid #191108; color:var(--ink);
  background-color:#c6b088;
  background-image:${FIBRE}, linear-gradient(170deg,#dccdA5 0%,#bda887 60%,#9c8760 100%);
  background-blend-mode:multiply,normal;
  box-shadow:0 14px 32px -10px rgba(0,0,0,.9);
  clip-path:polygon(7px 0,100% 0,100% calc(100% - 7px),calc(100% - 7px) 100%,0 100%,0 7px);
  opacity:0; transition:opacity .12s;
}
.ash-tt.on{ opacity:1; }
.ash-tt h4{ margin:0 0 4px; font-family:var(--uncial); font-size:12px; letter-spacing:.16em;
  text-transform:uppercase; font-weight:400; color:#3d2c15; }
.ash-tt .stat{ display:flex; justify-content:space-between; gap:14px; font-size:12px; color:var(--ink2); }
.ash-tt .ench{ margin-top:5px; padding-top:5px; border-top:1px solid rgba(60,42,20,.4);
  font-size:12px; font-style:italic; color:#4a3a6b; }
.ash-tt .desc{ margin-top:5px; font-size:12px; font-style:italic; color:var(--ink3); }
.ash-tt .cond{ height:4px; margin-top:7px; background:rgba(30,21,12,.45); border:1px solid #33240f; }
.ash-tt .cond i{ display:block; height:100%; background:linear-gradient(90deg,#5f7a63,#93b877); }
.ash-tt .cond.worn i{ background:linear-gradient(90deg,#8a5a1c,#c08a35); }
.ash-tt .cond.broken i{ background:linear-gradient(90deg,#6e1d13,#b03424); }

/* ----------------------------------------------------------- character/mag */

.ash-cols2{ display:grid; grid-template-columns:1fr 1fr; gap:8px 26px; }
.ash-cols3{ display:grid; grid-template-columns:repeat(3,1fr); gap:6px 22px; }
.ash-stat{ display:flex; align-items:baseline; gap:8px; font-size:14px; }
.ash-stat .k{ flex:1; color:var(--ink2); }
#ash-ui .leader{ flex:1; min-width:18px; border-bottom:1px dotted rgba(72,50,22,.55); transform:translateY(-3px); }
.ash-stat .v{ font-variant-numeric:tabular-nums; min-width:30px; text-align:right; }
.ash-stat .v.up{ color:#2f5a2f; } .ash-stat .v.down{ color:var(--bad); }

.ash-skill{ position:relative; padding:1px 0 3px; }
.ash-skill .line{ display:flex; align-items:baseline; gap:7px; font-size:13px; }
.ash-skill .k{ color:var(--ink2); } .ash-skill .k.major{ color:#3a2a12; font-weight:600; }
.ash-skill .k.minor{ color:#4b3a20; }
.ash-skill .v{ margin-left:auto; font-variant-numeric:tabular-nums; }
.ash-skill .prog{ height:2px; background:rgba(60,42,20,.24); margin-top:1px; }
.ash-skill .prog i{ display:block; height:100%; background:linear-gradient(90deg,var(--gold2),var(--gold)); }
.ash-spec{ font-family:var(--uncial); font-size:11px; letter-spacing:.22em; text-transform:uppercase;
  color:#5c4423; margin:10px 0 5px; border-bottom:1px solid rgba(60,42,20,.35); padding-bottom:3px; }

.ash-mult{ display:flex; gap:5px; }
.ash-mult button{
  pointer-events:auto; cursor:pointer; width:34px; padding:4px 0; border:1px solid #2b2013;
  background:rgba(255,246,216,.22); font-size:12px; font-variant-numeric:tabular-nums; color:var(--ink2);
}
.ash-mult button.sel{ background:linear-gradient(180deg,#d9c391,#a98f5c); color:#2b2013; border-color:#4a3720; }
.ash-mult button[disabled]{ opacity:.35; cursor:default; }

/* ---------------------------------------------------------------- dialogue */

.ash-portrait{
  width:132px; height:150px; flex:0 0 132px; border:1px solid #241a10; overflow:hidden; position:relative;
  background:linear-gradient(180deg,#3a2b1c,#150e08);
}
.ash-portrait svg{ width:100%; height:100%; display:block; }
.ash-disp{ margin-top:7px; }
.ash-disp .bar{ height:8px; border:1px solid #2b2013; background:rgba(20,14,8,.55); position:relative; overflow:hidden; }
.ash-disp .bar i{ display:block; height:100%; transition:width .4s; background:linear-gradient(90deg,#6e2118,#c8442c); }
.ash-disp.warm .bar i{ background:linear-gradient(90deg,#5f7a63,#93b877); }
.ash-disp .lbl{ display:flex; justify-content:space-between; font-size:11px; letter-spacing:.12em;
  text-transform:uppercase; color:var(--ink3); margin-top:3px; }
.ash-topics{ width:200px; flex:0 0 200px; }
.ash-topic{
  pointer-events:auto; cursor:pointer; display:block; width:100%; text-align:left; border:0;
  background:none; padding:3px 6px; font-size:14px; color:#3b4a6e; text-decoration:underline;
  text-decoration-color:rgba(59,74,110,.4); text-underline-offset:3px;
}
.ash-topic:hover{ background:rgba(120,92,48,.22); color:#26314a; }
.ash-topic.fresh{ color:#6a4b12; font-weight:600; }
.ash-topic.fresh::after{ content:' ✦'; color:var(--gold2); }
.ash-said{ color:var(--ink3); }
.ash-resp p{ margin:0 0 .8em; }
.ash-resp .who{ font-family:var(--uncial); font-size:11px; letter-spacing:.2em; text-transform:uppercase; color:#5c4423; }

/* ---------------------------------------------------------- journal / book */

.ash-page{ column-gap:34px; font-size:15px; line-height:1.62; text-align:justify; hyphens:auto; }
.ash-page.two{ column-count:2; }
.ash-page p{ margin:0 0 .75em; }
.ash-page .drop::first-letter{
  float:left; font-family:var(--uncial); font-size:44px; line-height:.82; padding:4px 7px 0 0; color:#6a3f16;
}
.ash-page h3{ font-family:var(--uncial); font-weight:400; font-size:14px; letter-spacing:.2em;
  text-transform:uppercase; color:#5c4423; margin:0 0 .7em; }
.ash-folio{ display:flex; justify-content:space-between; align-items:center; margin-top:10px;
  font-size:11px; letter-spacing:.2em; color:var(--ink3); }
.ash-turn{ animation:ash-turn .34s ease-in both; transform-origin:left center; }
@keyframes ash-turn{
  from{ transform:perspective(1400px) rotateY(-38deg); opacity:.25; filter:brightness(.7); }
  to{ transform:none; opacity:1; filter:none; }
}
.ash-entry{ margin-bottom:14px; }
.ash-entry .date{ font-size:11px; letter-spacing:.18em; text-transform:uppercase; color:var(--ink3); }
.ash-entry.done .name{ text-decoration:line-through; color:var(--ink3); }
.ash-entry .name{ font-family:var(--uncial); font-size:13px; letter-spacing:.12em; color:#4a3720; }

/* ---------------------------------------------------------------------- map */

.ash-map{ position:relative; flex:1; min-height:0; overflow:hidden; border:1px solid #2b2013;
  box-shadow:inset 0 0 40px rgba(60,40,16,.6); cursor:crosshair; pointer-events:auto; }
.ash-map canvas{ position:absolute; inset:0; width:100%; height:100%; display:block; image-rendering:auto; }
.ash-map .you{
  position:absolute; width:0; height:0; border-left:6px solid transparent; border-right:6px solid transparent;
  border-bottom:14px solid #7d1f14; transform-origin:50% 70%;
  filter:drop-shadow(0 1px 2px rgba(0,0,0,.7)); margin:-10px 0 0 -6px;
}
.ash-note{
  position:absolute; transform:translate(-50%,-100%); font-size:11px; color:#3a2a12; pointer-events:auto;
  cursor:pointer; white-space:nowrap; padding:1px 5px; background:rgba(232,216,178,.8);
  border:1px solid #6a5230; box-shadow:0 2px 5px rgba(0,0,0,.4);
}
.ash-note::after{ content:''; position:absolute; left:50%; bottom:-5px; width:1px; height:5px; background:#6a5230; }

/* ------------------------------------------------------------------- menus */

.ash-title{
  position:absolute; inset:0; display:flex; flex-direction:column; align-items:center; justify-content:center;
  gap:34px; pointer-events:auto;
  background:radial-gradient(70% 60% at 50% 34%, rgba(30,16,6,.30), rgba(4,3,2,.93) 100%);
}
.ash-title h1{
  margin:0; font-family:var(--uncial); font-size:clamp(30px,5.2vw,64px); font-weight:400;
  letter-spacing:.42em; text-indent:.42em; text-transform:uppercase;
  color:#e5d3a5; text-shadow:0 0 40px rgba(196,85,31,.42), 0 3px 0 rgba(0,0,0,.7);
}
.ash-title .rule{ width:min(420px,52vw); height:1px; background:linear-gradient(90deg,transparent,var(--gold2),transparent); }
.ash-title .sub{ font-size:11px; letter-spacing:.52em; text-transform:uppercase; color:#7d6b46; margin-top:-24px; }
.ash-title .menu{ display:flex; flex-direction:column; gap:9px; width:250px; }

.ash-slots{ display:grid; grid-template-columns:repeat(2,1fr); gap:9px; }
.ash-slotcard{
  display:flex; gap:10px; padding:7px; pointer-events:auto; cursor:pointer; text-align:left;
  border:1px solid #3a2b1a; background:rgba(70,52,28,.22); align-items:center;
}
.ash-slotcard:hover{ background:rgba(120,92,48,.3); }
.ash-slotcard.sel{ box-shadow:inset 0 0 0 1px var(--gold); }
.ash-slotcard .thumb{ width:86px; height:48px; flex:0 0 86px; border:1px solid #241a10; object-fit:cover;
  background:repeating-linear-gradient(135deg,#2c2114 0 6px,#241a11 6px 12px); }
.ash-slotcard .meta{ min-width:0; }
.ash-slotcard .nm{ font-size:13px; color:#3a2a12; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
.ash-slotcard .dt{ font-size:11px; color:var(--ink3); }
.ash-slotcard.empty .nm{ color:var(--ink3); font-style:italic; }

.ash-choice{
  pointer-events:auto; cursor:pointer; width:100%; text-align:left; border:1px solid transparent;
  background:none; padding:4px 8px; font-size:14px; color:var(--ink2);
}
.ash-choice:hover{ background:rgba(120,92,48,.22); }
.ash-choice.sel{ background:linear-gradient(90deg,rgba(160,124,62,.42),rgba(160,124,62,.06));
  border-color:rgba(90,66,30,.5); color:#33240f; }

.ash-blurb{ font-size:13px; font-style:italic; color:var(--ink2); line-height:1.55; }
.ash-hint{ font-size:11px; letter-spacing:.16em; text-transform:uppercase; color:var(--ink3); }
.ash-keys{ position:absolute; left:50%; transform:translateX(-50%); bottom:8px; font-size:10px;
  letter-spacing:.2em; text-transform:uppercase; color:rgba(190,170,128,.38);
  text-shadow:0 1px 3px #000; text-align:center; white-space:nowrap; }

.ash-cost{ display:flex; gap:16px; align-items:baseline; margin-top:8px; padding-top:7px;
  border-top:1px solid rgba(60,42,20,.4); }
.ash-cost .big{ font-family:var(--uncial); font-size:19px; color:#3a2a12; font-variant-numeric:tabular-nums; }
.ash-cost .lbl{ font-size:10px; letter-spacing:.2em; text-transform:uppercase; color:var(--ink3); }
.ash-cost .risk{ color:var(--bad); } .ash-cost .safe{ color:#2f5a2f; }

@media (prefers-reduced-motion: reduce){
  #ash-ui *, #ash-ui *::before, #ash-ui *::after{
    animation-duration:.001s !important; animation-iteration-count:1 !important; transition-duration:.001s !important;
  }
}
`;

/** Colour ramp shared by the map bake and the compass, kept next to the palette it belongs to. */
export const PARCHMENT_RAMP: readonly [number, number, number][] = [
  [104, 118, 122],
  [126, 134, 122],
  [176, 160, 118],
  [199, 178, 130],
  [186, 158, 108],
  [162, 128, 82],
  [138, 104, 66],
  [122, 92, 60],
];
