/**
 * ASHLANDS — core engine contracts.
 *
 * THIS FILE IS THE INTEGRATION BOUNDARY. Every subsystem is authored against
 * these interfaces and nothing else. Do not edit this file in a subsystem
 * task; if you need a contract change, report it instead.
 */
import type * as THREE from 'three';

/** Monotonic frame timing, shared by every system. */
export interface FrameTime {
  /** Seconds since previous frame, clamped to [0, 0.1] to survive tab stalls. */
  dt: number;
  /** Seconds since engine start. */
  elapsed: number;
  /** Integer frame counter since engine start. */
  frame: number;
}

/** In-world clock. 0 = midnight, 12 = noon. Drives sky, AI schedules, ambience. */
export interface WorldClock {
  /** Hour of day in [0, 24). */
  hour: number;
  /** Day index since campaign start. */
  day: number;
  /** How many in-world seconds pass per real second. */
  scale: number;
}

/**
 * Shared engine context handed to every system. Systems communicate through
 * this and the EventBus — never by importing each other directly. That rule is
 * what keeps subsystems independently authorable.
 */
export interface Ctx {
  renderer: THREE.WebGLRenderer;
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  time: FrameTime;
  clock: WorldClock;
  bus: EventBus;
  input: InputState;
  /** Registry lookup for cross-system queries. Prefer events where possible. */
  get<T extends System>(id: string): T | undefined;
  /** Viewport in device pixels, post-DPR. */
  size: { w: number; h: number; dpr: number };
}

/**
 * A subsystem. Systems are constructed cheaply, then `init` may do async work
 * (texture synthesis, mesh generation). `update` runs every frame in registry
 * order. Systems must be safe to `dispose` and re-`init`.
 */
export interface System {
  /** Stable unique id, e.g. 'terrain'. Used by Ctx.get. */
  readonly id: string;
  /** Lower runs first. Convention: render=-100, world=0, actors=100, ui=200. */
  readonly order?: number;
  init?(ctx: Ctx): Promise<void> | void;
  update?(ctx: Ctx): void;
  /** Called after the main scene render, for systems owning their own passes. */
  lateUpdate?(ctx: Ctx): void;
  resize?(ctx: Ctx): void;
  dispose?(): void;
}

/** Minimal typed pub/sub. Handlers must not throw. */
export interface EventBus {
  on<T = unknown>(evt: string, fn: (payload: T) => void): () => void;
  once<T = unknown>(evt: string, fn: (payload: T) => void): () => void;
  emit<T = unknown>(evt: string, payload?: T): void;
}

/** Snapshot of input for the current frame. Read-only to systems. */
export interface InputState {
  /** Physical key codes currently held, e.g. 'KeyW'. */
  held: ReadonlySet<string>;
  /** Keys that transitioned to down this frame. */
  pressed: ReadonlySet<string>;
  /** Accumulated pointer delta this frame, in pixels. */
  mouseDx: number;
  mouseDy: number;
  wheel: number;
  buttons: ReadonlySet<number>;
  pointerLocked: boolean;
}

/** Weather state published by the atmosphere system on 'weather'. */
export interface WeatherState {
  kind: 'clear' | 'cloudy' | 'overcast' | 'rain' | 'thunder' | 'ashstorm' | 'blight' | 'blizzard';
  /** 0..1 transition progress into `kind`. */
  blend: number;
  windDir: THREE.Vector2;
  windSpeed: number;
  /** 0..1, drives wetness in terrain/arch materials. */
  wetness: number;
  /** Linear-space sun radiance, for systems that need to match lighting. */
  sunColor: THREE.Color;
  sunDir: THREE.Vector3;
  /** Ambient/sky irradiance estimate. */
  ambient: THREE.Color;
  fogDensity: number;
}

/** Terrain query interface — used by flora, actors, physics, architecture. */
export interface TerrainQuery {
  /** World-space height at (x,z). Must be cheap; called thousands of times. */
  heightAt(x: number, z: number): number;
  /** World-space normal at (x,z). */
  normalAt(x: number, z: number, out?: THREE.Vector3): THREE.Vector3;
  /** Dominant surface material index at (x,z) — drives footstep audio + flora. */
  materialAt(x: number, z: number): number;
  /** Half-extent of the playable region in metres, centred on origin. */
  readonly extent: number;
}

/** Named surface materials, shared by terrain splat, footsteps and flora rules. */
export const enum Surface {
  Ash = 0,
  Rock = 1,
  Sand = 2,
  Grass = 3,
  Mud = 4,
  Lava = 5,
  Snow = 6,
  Stone = 7,
}

/** A PBR texture set produced by the material synthesis system. */
export interface PBRSet {
  albedo: THREE.Texture;
  normal: THREE.Texture;
  /** Packed: r=ambient occlusion, g=roughness, b=metalness, a=height. */
  arm: THREE.Texture;
  dispose(): void;
}
